// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSort() {
  return window['go']['main']['App']['CancelSort']();
}

export function DeleteFiles(arg1) {
  return window['go']['main']['App']['DeleteFiles'](arg1);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLifetimeStats() {
  return window['go']['main']['App']['GetLifetimeStats']();
}

export function HasUndoHistory() {
  return window['go']['main']['App']['HasUndoHistory']();
}

export function ImportConfig() {
  return window['go']['main']['App']['ImportConfig']();
}

export function IsSystemPath(arg1) {
  return window['go']['main']['App']['IsSystemPath'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanDuplicates(arg1) {
  return window['go']['main']['App']['ScanDuplicates'](arg1);
}

export function ScanFolder(arg1) {
  return window['go']['main']['App']['ScanFolder'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectTargetFolder() {
  return window['go']['main']['App']['SelectTargetFolder']();
}

export function SortFolder(arg1) {
  return window['go']['main']['App']['SortFolder'](arg1);
}

export function UndoLastSort() {
  return window['go']['main']['App']['UndoLastSort']();
}
