// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {stats} from '../models';
import {cleaner} from '../models';
import {main} from '../models';

export function CancelSort():Promise<void>;

export function DeleteFiles(arg1:Array<string>):Promise<number>;

export function ExportConfig():Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetLifetimeStats():Promise<stats.LifetimeStats>;

export function HasUndoHistory():Promise<boolean>;

export function ImportConfig():Promise<config.Config>;

export function IsSystemPath(arg1:string):Promise<boolean>;

export function ResetConfig():Promise<config.Config>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function ScanDuplicates(arg1:string):Promise<Array<cleaner.DuplicateGroup>>;

export function ScanFolder(arg1:string):Promise<main.ScanResponse>;

export function SelectFolder():Promise<string>;

export function SelectTargetFolder():Promise<string>;

export function SortFolder(arg1:string):Promise<void>;

export function UndoLastSort():Promise<number>;
